## Importando os dados

In [21]:
# abrir a conexão com o banco de dados
import sqlite3
import pandas as pd
conn = sqlite3.connect("database.db")

In [22]:
# consulta os dados no banco de dados
consulta_atividade = "SELECT * FROM flight_activity LIMIT 10"
df_atividade = pd.read_sql_query(consulta_atividade, conn)

In [20]:
# fecha a conexão com o banco de dados
conn.close()

In [ ]:
df_atividade.head()

In [26]:
# selecionme as colunas loyalty_number, year, month, flights_booked, total_flights, distance e
# points_accumulated da tabela "flight_activity"
consulta_atividade = """
  SELECT
    loyalty_number,
    year,
    month,
    flights_booked,
    total_flights,
    distance,
    points_accumulated
  FROM
    flight_activity

"""
df_atividade = pd.read_sql_query(consulta_atividade, conn)
df_atividade.head()

,loyalty_number,year,month,flights_booked,total_flights,distance,points_accumulated
0,100018,2017,1,3,3,1521,152.0
1,100102,2017,1,10,14,2030,203.0
2,100140,2017,1,6,6,1200,120.0
3,100214,2017,1,0,0,0,0.0
4,100272,2017,1,0,0,0,0.0

In [ ]:
# selecione as mesmas colunas, porém, recupere somente as linhas cuja coluna distance for
# maior que 2000.
consulta_atividade = """
  SELECT
    loyalty_number,
    year,
    month,
    flights_booked,
    total_flights,
    distance,
    points_accumulated
  FROM
    flight_activity
  WHERE distance > 2000

"""
df_atividade = pd.read_sql_query(consulta_atividade, conn)
df_atividade.head()

In [ ]:
# selecione as mesmas colunas, porém, recupere somente as linhas cuja coluna distance for
# maior que 2000 e a coluna month for igual a 9.
consulta_atividade = """
  SELECT
    loyalty_number,
    year,
    month,
    flights_booked,
    total_flights,
    distance,
    points_accumulated
  FROM
    flight_activity
  WHERE distance > 2000 AND month == 9

"""
df_atividade = pd.read_sql_query(consulta_atividade, conn)
df_atividade.head()

In [ ]:
# selecione as mesmas colunas, porém, recupere somente as linhas cuja coluna distance for
# maior que 2000 ou a coluna points_accumulated for menor que 100.
consulta_atividade = """
  SELECT
    loyalty_number,
    year,
    month,
    flights_booked,
    total_flights,
    distance,
    points_accumulated
  FROM
    flight_activity
  WHERE distance > 2000 OR points_accumulated < 100

"""
df_atividade = pd.read_sql_query(consulta_atividade, conn)
df_atividade.head()

In [ ]:
# selecione as mesmas colunas, porém, recupere somente as linhas cuja coluna loyalty_card for
#igual a Star da tabela "flight_loyalty_history".
consulta_atividade = """
  SELECT
    *
  FROM
    flight_loyalty_history
  WHERE loyalty_card == 'Star'

"""
df_atividade = pd.read_sql_query(consulta_atividade, conn)
df_atividade.head()

## Exercícios da Aula 01

In [ ]:
# EXERCÌCIO 1
# selecione as colunas loyalty_number, country, city, gender, loyalty_card, salary
# da tabela flight_loyalty_history
consulta_atividade = """
  SELECT
    loyalty_number,
    country,
    city,
    gender,
    loyalty_card, salary
  FROM
    flight_loyalty_history


"""
df_atividade = pd.read_sql_query(consulta_atividade, conn)
df_atividade.head()

In [ ]:
# EXERCÌCIO 2
# selecione as mesmas colunas, porém, recupere somente as linhas cuja coluna gender
# for igual a Female da tabela flight_loyalty_history
consulta_atividade = """
  SELECT
    loyalty_number,
    country,
    city,
    gender,
    loyalty_card,
    salary
  FROM
    flight_loyalty_history
  WHERE
    gender = 'Female'

"""
df_atividade = pd.read_sql_query(consulta_atividade, conn)
df_atividade.head()

In [50]:
# EXERCÌCIO 3
# selecione as colunas loyalty_number, year, month, distance,
# flights_booked e total_flights da tabela flight_activity, e recupere
# somente as linhas cuja coluna flights_booked for maior que 10 e a
# coluna flights_booked for menor que 12, da tabela flight_activity
consulta_atividade = """
  SELECT
    loyalty_number,
    year,
    month,
    distance,
    flights_booked,
    total_flights
  FROM
    flight_activity
  WHERE
     flights_booked > 10 AND flights_booked < 12

"""
df_atividade = pd.read_sql_query(consulta_atividade, conn)
df_atividade.head()

   loyalty_number  year  month  distance  flights_booked  total_flights
0          100727  2017      1      1144              11             11
1          100883  2017      1      3124              11             11
2          101515  2017      1      1100              11             11
3          101594  2017      1      3399              11             11
4          104353  2017      1      1343              11             17